## Your Mileage May Vary
- NightmareFuel
- TearJerker
- FandomSpecificPlot
- FoeYay
- ThatOneLevel
- GameBreaker
- FridgeLogic
- FridgeHorror
- FridgeBrilliance
- Fridge
- Headscratchers
- SidetrackedByTheGoldenSaucer

## Positive Opinions
- SugarWiki
- AwesomeMusic
- MostWonderfulSound
- AndTheFandomRejoiced
- SweetDreamsFuel
- HeReallyCanAct
- NeedsMoreLove
- BetterThanItSounds

## Negative Opinions
- DarthWiki
- WorseThanItSounds
- MostAnnoyingSound

## Tvtropes Metadata
- Laconic
- QuoteSource
- VideoSource
- UsefulNotes
- Quotes
- Summary
- NoRealLife
- Analysis
- ImageLinks
- FanficRecs

## Characters
## Tvtropes sometimes has pages specifically for characters
## should I be adding these to the relevant media?
- Characters

## Tropers having fun
- JustForFun
- RoleAssociation
- IThoughtItMeant
- Pantheon

## Depreciated
- WarpThatAesop