## Opinions
- FoeYay
- JustForFun
- ThatOneLevel
- GameBreaker
## Your Mileage May Vary
- NightmareFuel
- TearJerker
- FandomSpecificPlot
## Positive Opinions
- SugarWiki
- AwesomeMusic
- MostWonderfulSound
- AndTheFandomRejoiced
- SweetDreamsFuel
- HeReallyCanAct
- NeedsMoreLove
## Negative Opinions
- DarthWiki
- WorseThanItSounds

## Tvtropes Metadata
- Laconic
- QuoteSource
- VideoSource
- UsefulNotes

## Depreciated
- WarpThatAesop